name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: itzg/minecraft-server
      ports:
        - 25565:25565
      env:
        EULA: "TRUE"
    steps:
      - name: Get IP
        run: ip a
      - name: Get IP
        run: curl ipconfig.io
      - name: Start Server
        run: cd / && ./start

