name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  minecraft-server:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    steps:
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    container:
      image: itzg/minecraft-server
      ports:
        - 25565:25565
      env:
        EULA: "TRUE"
    steps:
      - name: Start Server
        run: cd / && ./start


