name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: itzg/minecraft-server
      ports:
        - 25565
    steps:
      - name: Print the input tag to STDOUT
        run: watch date

