name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  minecraft-server:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    steps:
      - name: setup
        run: |
          whoami
          mkdir ~/.ssh
          touch ~/.ssh/authorized_keys
          echo "${{ vars.PUB_KEY }}" >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh/
          mkdir ~/data
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: |
            --hostname minecraft
            --accept-dns=true
            --accept-routes=true

      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/data
          key: minecraft-${{ github.run_number }}
          restore-keys: |
            minecraft-

      - name: Minecraft
        run: |
          docker run -d -it -p 25565:25565 -p 25575:25575 -v ~/data:/data -e MEMORY=4G -e EULA=TRUE itzg/minecraft-server

      - name: Wait
        run: |
          tail -f /dev/null

      - name: save cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: |
            ~/data
          key: minecraft-${{ github.run_number }}


